metadatablock.name=customCAFEQualityChecklist
metadatablock.displayName=Quality Checklist
metadatablock.displayFacet=CAFE

datasetfieldtype.cafeChecklistReadmeIncluded.title=Review the CAFE Recommended README Template. Are all applicable fields from the template included in this submission description or an attached ReadMe?
datasetfieldtype.cafeChecklistReadmeIncluded.description=Indicate whether the ReadMe has been completed for this deposit. See description above for more information.
datasetfieldtype.cafeChecklistReadmeIncluded.watermark=

datasetfieldtype.cafeChecklistDataDictionaryProvided.title=Does this submission include a data dictionary describing all variables, units, etc. as applicable?
datasetfieldtype.cafeChecklistDataDictionaryProvided.description=Indicate whether a data dictionary has been completed for this deposit. See description above for more information.
datasetfieldtype.cafeChecklistDataDictionaryProvided.watermark=

datasetfieldtype.cafeChecklistSubmissionGuidelines.title=Review the Extracted Data Collection Submission Guidelines. Have you completed all required fields in line with the submission guidance?
datasetfieldtype.cafeChecklistSubmissionGuidelines.description=Indicate whether the Guidelines has been followed for this deposit. See description above for more information.
datasetfieldtype.cafeChecklistSubmissionGuidelines.watermark=

datasetfieldtype.cafeChecklistSupportingArtifacts.title=Does this submission include a screenshot of the site from which data were downloaded, and any technical documentation and/or data dictionaries that were distributed along with the extracted dataset (as available)?
datasetfieldtype.cafeChecklistSupportingArtifacts.description=Indicate whether these critical data extraction components have been included for this deposit. See description above for more information.
datasetfieldtype.cafeChecklistSupportingArtifacts.watermark=

controlledvocabulary.cafeChecklistReadmeIncluded.yes=Yes
controlledvocabulary.cafeChecklistReadmeIncluded.no=No
controlledvocabulary.cafeChecklistReadmeIncluded.pending_addition=Pending addition

controlledvocabulary.cafeChecklistDataDictionaryProvided.yes=Yes
controlledvocabulary.cafeChecklistDataDictionaryProvided.no=No
controlledvocabulary.cafeChecklistDataDictionaryProvided.pending_addition=Pending addition

controlledvocabulary.cafeChecklistSubmissionGuidelines.yes=Yes
controlledvocabulary.cafeChecklistSubmissionGuidelines.no=No
controlledvocabulary.cafeChecklistSubmissionGuidelines.pending_addition=Pending addition

controlledvocabulary.cafeChecklistSupportingArtifacts.yes=Yes
controlledvocabulary.cafeChecklistSupportingArtifacts.no=No
controlledvocabulary.cafeChecklistSupportingArtifacts.not_applicable=Not applicable
controlledvocabulary.cafeChecklistSupportingArtifacts.pending_addition=Pending addition
