metadatablock.name=customCIESIN
metadatablock.displayName=CIESIN Metadata Block
metadatablock.displayFacet=CIESIN
datasetfieldtype.horizontalCoordinateSystemDefinition.title=Horizontal Coordinate System Definition
datasetfieldtype.latitudeResolution.title=Latitude Resolution
datasetfieldtype.longitudeResolution.title=Longitude Resolution
datasetfieldtype.geographicCoordinateUnits.title=Geographic Coordinate Units
datasetfieldtype.geodeticModel.title=Geodetic Model
datasetfieldtype.horizontalDatumName.title=Horizontal Datum Name
datasetfieldtype.ellipsoidName.title=Ellipsoid Name
datasetfieldtype.directSpatialReferenceMethod.title=Direct Spatial Reference Method
datasetfieldtype.rasterObjectType.title=Raster Object Type
datasetfieldtype.rasterObjectRowCount.title=Raster Object Row Count
datasetfieldtype.rasterObjectColumnCount.title=Raster Object Column Count
datasetfieldtype.rasterObjectVerticalCount.title=Raster Object Vertical Count
datasetfieldtype.horizontalCoordinateSystemDefinition.description=The reference frame or system from which linear or angular quantities are measured and assigned to the position that a point occupies
datasetfieldtype.latitudeResolution.description=The minimum difference between two adjacent latitude values expressed in Geographic Coordinate Units of measure
datasetfieldtype.longitudeResolution.description=The minimum difference between two adjacent longitude values expressed in Geographic Coordinate Units of measure
datasetfieldtype.geographicCoordinateUnits.description=The unit of measure used for the latitude and longitude values
datasetfieldtype.geodeticModel.description=The parameters for the shape of the earth
datasetfieldtype.horizontalDatumName.description=The identification given to the reference system used for defining the coordinates of points
datasetfieldtype.ellipsoidName.description=The identification given to established representations of the Earth's shape
datasetfieldtype.directSpatialReferenceMethod.description=The system of objects used to represent space in the Dataset
datasetfieldtype.rasterObjectType.description=The raster spatial objects used to locate zero-, two-, or three-dimensional locations in the Dataset
datasetfieldtype.rasterObjectRowCount.description=The maximum number of raster objects along the ordinate (y) axis
datasetfieldtype.rasterObjectColumnCount.description=The maximum number of raster objects along the abscissa (x) axis
datasetfieldtype.rasterObjectVerticalCount.description=The maximum number of raster objects along the vertical (z) axis
datasetfieldtype.horizontalCoordinateSystemDefinition.watermark=
datasetfieldtype.latitudeResolution.watermark=
datasetfieldtype.longitudeResolution.watermark=
datasetfieldtype.geographicCoordinateUnits.watermark=
datasetfieldtype.geodeticModel.watermark=
datasetfieldtype.horizontalDatumName.watermark=
datasetfieldtype.ellipsoidName.watermark=
datasetfieldtype.directSpatialReferenceMethod.watermark=
datasetfieldtype.rasterObjectType.watermark=
datasetfieldtype.rasterObjectRowCount.watermark=
datasetfieldtype.rasterObjectColumnCount.watermark=
datasetfieldtype.rasterObjectVerticalCount.watermark=