metadatablock.name=rubric_customUNCDataReview
metadatablock.displayName=UNC Data Review
metadatablock.displayFacet=
datasetfieldtype.uncDataReviewAccuracy.title=Accuracy
datasetfieldtype.uncDataReviewReliability.title=Reliability
datasetfieldtype.uncDataReviewObjectivity.title=Objectivity
datasetfieldtype.uncDataReviewReproducibility.title=Reproducibility
datasetfieldtype.uncDataReviewTransparency.title=Transparency
datasetfieldtype.uncDataReviewReputationForQuality.title=Reputation for Quality
datasetfieldtype.uncDataReviewProtectionFromUnauthorizedDisclosure.title=Protection from Unauthorized Disclosure
datasetfieldtype.uncDataReviewConsent.title=Consent
datasetfieldtype.uncDataReviewCompliance.title=Compliance
datasetfieldtype.uncDataReviewRubricSummary.title=Rubric Summary
datasetfieldtype.uncDataReviewAccuracy.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewReliability.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewObjectivity.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewReproducibility.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewTransparency.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewReputationForQuality.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewProtectionFromUnauthorizedDisclosure.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewConsent.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewCompliance.description=Self defined definition by respondents
datasetfieldtype.uncDataReviewRubricSummary.description=Narrative summary of all quality indicators in the rubric
datasetfieldtype.uncDataReviewAccuracy.watermark=
datasetfieldtype.uncDataReviewReliability.watermark=
datasetfieldtype.uncDataReviewObjectivity.watermark=
datasetfieldtype.uncDataReviewReproducibility.watermark=
datasetfieldtype.uncDataReviewTransparency.watermark=
datasetfieldtype.uncDataReviewReputationForQuality.watermark=
datasetfieldtype.uncDataReviewProtectionFromUnauthorizedDisclosure.watermark=
datasetfieldtype.uncDataReviewConsent.watermark=
datasetfieldtype.uncDataReviewCompliance.watermark=
datasetfieldtype.uncDataReviewRubricSummary.watermark=
