metadatablock.name=rubric_customNYUProducerQuality
metadatablock.displayName=NYU Producer Quality Review
metadatablock.displayFacet=
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreLLM.title=Average Aggregate Score (Expert)
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreHumanReponse.title=Average Aggregate Score (Community)
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationLLM.title=Standard Deviation (Expert)
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationHumanResponse.title=Standard Deviation (Community)
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreLLM.title=Average Aggregate Score (Expert)
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreHumanReponse.title=Average Aggregate Score (Community)
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationLLM.title=Standard Deviation (Expert)
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationHumanResponse.title=Standard Deviation (Community)
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreLLM.title=Average Aggregate Score (Expert)
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreHumanReponse.title=Average Aggregate Score (Community)
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationLLM.title=Standard Deviation (Expert)
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationHumanResponse.title=Standard Deviation (Community)
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreLLM.title=Average Aggregate Score (Expert)
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreHumanReponse.title=Average Aggregate Score (Community)
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationLLM.title=Standard Deviation (Expert)
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationHumanResponse.title=Standard Deviation (Community)
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreLLM.title=Average Aggregate Score (Expert)
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreHumanReponse.title=Average Aggregate Score (Community)
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationLLM.title=Standard Deviation (Expert)
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationHumanResponse.title=Standard Deviation (Community)
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreLLM.description=
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreHumanReponse.description=
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationLLM.description=
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationHumanResponse.description=
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreLLM.description=
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreHumanReponse.description=
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationLLM.description=
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationHumanResponse.description=
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreLLM.description=
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreHumanReponse.description=
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationLLM.description=
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationHumanResponse.description=
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreLLM.description=
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreHumanReponse.description=
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationLLM.description=
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationHumanResponse.description=
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreLLM.description=
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreHumanReponse.description=
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationLLM.description=
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationHumanResponse.description=
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreLLM.watermark=
datasetfieldtype.nyuDataReviewAccuracyAverageAggregateScoreHumanReponse.watermark=
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationLLM.watermark=
datasetfieldtype.nyuDataReviewAccuracyStandardDeviationHumanResponse.watermark=
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreLLM.watermark=
datasetfieldtype.nyuDataReviewReliabilityAverageAggregateScoreHumanReponse.watermark=
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationLLM.watermark=
datasetfieldtype.nyuDataReviewReliabilityStandardDeviationHumanResponse.watermark=
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreLLM.watermark=
datasetfieldtype.nyuDataReviewObjectivityAverageAggregateScoreHumanReponse.watermark=
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationLLM.watermark=
datasetfieldtype.nyuDataReviewObjectivityStandardDeviationHumanResponse.watermark=
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreLLM.watermark=
datasetfieldtype.nyuDataReviewReputationForQualityAverageAggregateScoreHumanReponse.watermark=
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationLLM.watermark=
datasetfieldtype.nyuDataReviewReputationForQualityStandardDeviationHumanResponse.watermark=
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreLLM.watermark=
datasetfieldtype.nyuDataReviewDataProtectionAverageAggregateScoreHumanReponse.watermark=
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationLLM.watermark=
datasetfieldtype.nyuDataReviewDataProtectionStandardDeviationHumanResponse.watermark=
